pheralb/svgl

- data/svgs.json
- package-lock.json
- public/library/speackme.svg
> Upgrade - Speack.me

- src/components/search.tsx
- src/interfaces/components.ts
- src/layout/header/index.tsx
Hi!! 😊
This feature apply autofocus in the search input when user open the search box. This is only available when the toggle button is visible! (Not for mobile)
**📸 Preview**
**Este repo esta para lamerlo!! ⚡️🚀 Muchas gracias por crearlo ❤️**
> Add autofocus when open search box

- data/svgs.json
- public/library/css.svg
- public/library/html5.svg
> ✨ add html & css logos

- src/routes/+layout.server.ts
- src/routes/+layout.svelte
- src/utils/getStarsRepository.ts
Add stars count repository in sidebar.
> Add: stars count repository

- src/data/svgs.ts
- static/library/dub.svg
Incredible work on this project @pheralb! Adding [Dub](http://dub.co/)'s logo here :)
> Add Dub.co logo

- src/data/svgs.ts
- static/library/opera.svg
Opera Browser Logo
Source: https://brand.opera.com/1472-2/opera-logos/
> Adding opera logo

- src/data/svgs.ts
- static/library/front.svg
Adds the Front.com logo
Sourced from the [Front.com press kit](https://front.com/press)
> Adds Front.com logo

- README.md
- src/components/navbar.svelte
- src/server/redis.ts
> ✨ Add figma plugin.

- src/data/svgs.ts
- static/library/trust.svg
- static/library/workos-light.svg
- static/library/workos.svg
+ Added **[WorkOS](https://workos.com)** and **[Trust Wallet](https://trustwallet.com)**
> + Added new icons

- src/data/svgs.ts
+ Fixed **WorkOS** dark/light variants
> + Transformed WorkOS Dark and Light Variants

- src/data/svgs.ts
- static/library/whop-light.svg
- static/library/whop.svg
✨ Added **[Whop](https://whop.com)**
> 🚀 Added New Icon

- src/components/search.svelte
> Add input hotkey `command + k` & `control + k` script

- package.json
- pnpm-lock.yaml
- src/routes/+page.svelte
- src/routes/directory/[slug]/+page.svelte
https://github.com/pheralb/svgl/assets/75478661/a005a769-7a2b-48b6-b87a-82721419cadd
Add a search URL parameter feature to support the following functionalities:
-  Reloading with the "keep search" parameter
-  Shareable search URL
> Add search url parameter feature

- src/ui/styles.ts
> Fix `Accept` button layout

- src/data/svgs.ts
- static/library/buildship.svg
- Add logo for BuildShip (https://buildship.com)
> Add BuildShip logo

- src/data/svgs.ts
Delete the duplicate Vitest logo data
> 🫡  Delete the duplicate Vitest logo data

- src/components/svgCard.svelte
- src/routes/+page.svelte
Fix the error that occurs when searching for an SVG with a wordmark and when searching for another SVG without a wordmark, as this causes the image to break.
**Before:**
https://github.com/user-attachments/assets/f57409f6-1f85-4826-a413-f6cfc0bc5add
**After:**
https://github.com/user-attachments/assets/5c84909b-7609-4e27-ad45-8fe9eecfeaac
> ⚙️ Fix wordmark SVG error

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- src/app.css
- src/components/copySvg.svelte
- src/components/svgCard.svelte
- src/components/warning.svelte
- src/data/svgs.ts
- src/docs/api.md
- src/routes/api/+page.svelte
- src/types/svg.ts
- src/ui/popover/popover-content.svelte
- svelte.config.js
- ✍️ Update warning message + add message to copy svg component
- ✨ Add support for product brand guidelines + 📝 Add brand guidelines section + fixed ``Request Logo`` url
- 📝 Create custom pull request template
- 🎨 New light/dark theme for Shiki + Update codeblocks
> ✨ New app improvements

- src/data/svgs.ts
- static/library/base-ui-dark.svg
- static/library/base-ui.svg
- **Title**: Base UI
- **Category**: Library
- **Website URL**: https://base-ui.com
- **Description**: Unstyled React components for building accessible user interfaces. From the creators of Radix, Floating UI, and MUI. An emerging worthy competitor to Radix UI
> 📦 Add Base UI SVG

- src/data/svgs.ts
- src/types/categories.ts
- static/library/terraform.svg
- **Title**: terraform
- **Category**: software, language, iac
- **Website URL**: https://terraform.io
- **Description**: Infrastructure as Code tool
> feat: add terraform logo

- src/data/svgs.ts
- src/types/categories.ts
⚙️ Fix Terraform SVG route & category
**Before**
**After**
> ⚙️ Fix Terraform SVG route & category

- package.json
- pnpm-lock.yaml
- src/components/copySvg.svelte
- src/components/downloadSvg.svelte
- src/utils/prefixSvgIds.ts
Fix duplicate IDs in various SVG files to resolve display issues.
Close #690.
> ⚙️ fix: resolve duplicate id display issue

- src/data/svgs.ts
👋 hi all! 
DevRel for Replit here, moving our category from software -> AI :)
> Move Replit from `software` -> `AI` category
